watcher_prover:
  hosts:
    watcher_prover_0:
      ansible_host: "{{ lookup('env','WATCHER_PROVER_HOST') }}"
      ansible_user: admin
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "{{ lookup('env','ANSIBLE_SSH_PKEY') }}"
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
