[workspace]
members = [
    "execution_engine",
    "rpc_endpoint",
    "store", 
    "crypto", 
    "network", 
    "mempool",
    "consensus", 
    "node",
    "sequencer",
    "types",
]
resolver = "2"
