networks:
  frontend:
    ipam:
      config:
        - subnet: 172.27.0.0/24

services:
  sequencer_node0:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.10
    ports:
      - 10000:10008
    volumes:
      - ./sequencer/config/sequencer_node0.json:/sequencer/config/sequencer_node0.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node0.json --committee /sequencer/config/committee.json --store /sequencer/db0

  sequencer_node1:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.11
    ports:
      - 10001:10008
    volumes:
      - ./sequencer/config/sequencer_node1.json:/sequencer/config/sequencer_node1.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node1.json --committee /sequencer/config/committee.json --store /sequencer/db1

  sequencer_node2:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.12
    ports:
      - 10002:10008
    volumes:
      - ./sequencer/config/sequencer_node2.json:/sequencer/config/sequencer_node2.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node2.json --committee /sequencer/config/committee.json --store /sequencer/db2

  sequencer_node3:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.13
    ports:
      - 10003:10008
    volumes:
      - ./sequencer/config/sequencer_node3.json:/sequencer/config/sequencer_node3.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node3.json --committee /sequencer/config/committee.json --store /sequencer/db3

  watcher_prover:
    build: ./watcher_prover
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres:5432/watcher_prover_dev
      - SECRET_KEY_BASE=IVx1FJb5Fg34MApqVRoSOFx/2PdNTnJRU5w1X/2A1G3E8qJKhLMGI5GJGPYglP1e
      - RPC_HOST=sequencer_node0
      - RPC_PORT=10008
      - PROVER_STORAGE=local
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - watcher

  postgres:
    container_name: watcher_prover_dev_db
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=watcher_prover_dev_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres

volumes:
  pg_data:
