networks:
  frontend:
    ipam:
      config:
        - subnet: 172.27.0.0/24

services:
  sequencer_node0:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.10
    volumes:
      - ./sequencer/config/sequencer_node0.json:/sequencer/config/sequencer_node0.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node0.json --committee /sequencer/config/committee.json --store /sequencer/db0

  sequencer_node1:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.11
    volumes:
      - ./sequencer/config/sequencer_node1.json:/sequencer/config/sequencer_node1.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node1.json --committee /sequencer/config/committee.json --store /sequencer/db1

  sequencer_node2:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.12
    volumes:
      - ./sequencer/config/sequencer_node2.json:/sequencer/config/sequencer_node2.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node2.json --committee /sequencer/config/committee.json --store /sequencer/db2

  sequencer_node3:
    build:
      context: ./sequencer/
    networks:
      frontend:
        ipv4_address: 172.27.0.13
    volumes:
      - ./sequencer/config/sequencer_node3.json:/sequencer/config/sequencer_node3.json
      - ./sequencer/config/committee.json:/sequencer/config/committee.json
    command: /sequencer/node -vvv run --keys /sequencer/config/sequencer_node3.json --committee /sequencer/config/committee.json --store /sequencer/db3
