services:
  watcher_prover:
    build: .
    ports:
      - "4000:4000"
    environment:
      - RPC_API_HOST=http://host.docker.internal:9944
      - DATABASE_URL=ecto://postgres:postgres@postgres:5432/watcher_prover_dev
      - SECRET_KEY_BASE=IVx1FJb5Fg34MApqVRoSOFx/2PdNTnJRU5w1X/2A1G3E8qJKhLMGI5GJGPYglP1e
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - watcher

  postgres:
    container_name: watcher_prover_dev_db
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=watcher_prover_dev_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      default:
        aliases:
          - postgres

volumes:
  pg_data:
