- name: Sequencer node
  hosts: nodes
  any_errors_fatal: true


  pre_tasks:
    - name: Install apt dependencies
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - curl
          - gcc
          - git
          - libclang-dev
          - g++
          - gnupg
          - wget
          - ufw

    - name: Install LLVM 16 sources
      become: true
      become_user: root
      ansible.builtin.shell: |
        echo "deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-16 main" > /etc/apt/sources.list.d/llvm-16.list
        echo "deb-src http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-16 main" >> /etc/apt/sources.list.d/llvm-16.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

    - name: Install LLVM 16
      become_user: root
      become: true
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - llvm-16
          - libmlir-16-dev
          - mlir-16-tools
          - libpolly-16-dev


    - name: Install rust
      ansible.builtin.shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly-2023-06-19

    - name: Enable systemd linger for {{ ansible_user }} user
      become: true
      become_user: root
      ansible.builtin.shell: |
        loginctl enable-linger {{ ansible_user }}

    - name: Create .ssh for {{ ansible_user }} user
      ansible.builtin.file:
        state: directory
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        path: /home/{{ ansible_user }}/.ssh

    - name: Set server hostname
      become: true
      become_user: root
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'

    - name: Clone starknet_stack repo
      ansible.builtin.git:
        repo: https://github.com/lambdaclass/starknet_stack.git
        version: main
        dest: /home/{{ ansible_user }}/starknet_stack

    - name: Build starknet_stack sequencer
      args:
        chdir: /home/{{ ansible_user }}/starknet_stack/sequencer
      ansible.builtin.shell: |
        set -ex
        export PATH="/home/{{ ansible_user }}/.cargo/bin:${PATH}"
        export MLIR_SYS_160_PREFIX=/usr/lib/llvm-16
        cargo +nightly-2023-06-19 build --features benchmark --release
        cargo +nightly-2023-06-19 build --bin client --features benchmark --release

    - name: Create {{ ansible_user }} user systemd directory
      ansible.builtin.file:
        state: directory
        path: /home/{{ ansible_user }}/.config/systemd/user

    - name: Install systemd service
      ansible.builtin.template:
        src: sequencer.service.j2
        dest: /home/{{ ansible_user }}/.config/systemd/user/sequencer.service
