- name: Sequencer node
  hosts: nodes
  any_errors_fatal: true


  pre_tasks:
    - name: Install apt dependencies
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - curl
          - gcc
          - libclang-dev
          - g++
          - gnupg
          - wget
          - ufw

    - name: Install LLVM 16 sources
      become_user: root
      ansible.builtin.shell: |
        echo "deb http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-16 main" > /etc/apt/sources.list.d/llvm-16.list
        echo "deb-src http://apt.llvm.org/bullseye/ llvm-toolchain-bullseye-16 main" >> /etc/apt/sources.list.d/llvm-16.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

    - name: Install LLVM 16
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - llvm-16
          - libmlir-16-dev
          - mlir-16-tools
          - libpolly-16-dev

    - name: Clone starknet stack sequencer

    - name: Add deploy group
      ansible.builtin.group:
        name: deploy
        state: present

    - name: Add sequencer user
      ansible.builtin.user:
        name: sequencer
        shell: /bin/bash
        groups: deploy

    - name: Install rust
      become_user: sequencer
      ansible.builtin.shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=nightly-2023-06-19

    - name: Enable systemd linger for sequencer user
      become_user: root
      ansible.builtin.shell: |
        loginctl enable-linger sequencer

    - name: Create .ssh for sequencer user
      ansible.builtin.file:
        state: directory
        owner: sequencer
        group: deploy
        path: /home/sequencer/.ssh

    - name: Set server hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'


