[package]
name = "execution_engine"
authors = ["LambdaClass <hello@lambdaclass.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = { version = "0.8.1", features = ["cairo-1-hints"]}
cairo-lang-starknet = { version = "2.0.2", default-features = false }
serde_json = "1.0.61"