[package]
name = "node"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>", "LambdaClass <hello@lambdaclass.com>"]
edition = "2018"
publish = false

[dependencies]
cairo-felt = "0.8.6"
cairo-lang-compiler = "2.2.0"
cairo-lang-sierra = "2.2.0"
num-bigint = "0.4.3"
tokio = { version = "1.1.0", features = ["time", "macros", "net", "rt-multi-thread"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
log = "0.4.0"
bytes = "1.0.1"
bincode = "1.3.1"
futures = "0.3.8"
clap = { version = "3.2.17", features = ["derive"] }
env_logger = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
rand = "0.7.3"
thiserror = "1.0.46"
anyhow = "1.0.38"
rpc_endpoint = {path = "../rpc_endpoint" }
jsonrpsee = { version="0.18.2", features = ["server", "macros"] }
crypto = { path = "../crypto" }
store = { path = "../store" }
consensus = { path = "../consensus" }
mempool = { path = "../mempool" }
sequencer = { path = "../sequencer" }
execution_engine = {path = "../execution_engine" }

[features]
benchmark = ["consensus/benchmark", "mempool/benchmark"]

[[bin]]
name = "client"
path = "src/client.rs"
required-features = ["benchmark"]
